---
driver_plugin: vagrant
provisioner: chef_zero

platforms:
- name: centos-6.4_chef-11.4.4
  driver_config:
    box: opscode-centos-6.4_chef-11.4.4
    box_url:  https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.4_chef-11.4.4.box
- name: ubuntu-12.04_chef-11.4.4
  driver_config:
    box: opscode-ubuntu-12.04_chef-11.4.4
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_chef-11.4.4.box

suites:
- name: controller
  run_list:
    - recipe[ktc-testing]
    - recipe[etcd::compile_time]
    - recipe[ktc-monitor::client]
    - recipe[ktc-database]
    - recipe[ktc-memcached]
    - recipe[ktc-messaging]
    - recipe[ktc-identity]
    - recipe[ktc-network]
  attributes:
    etcd:
      args: '-c 127.0.0.1:4001 -s 127.0.0.1:7001 -f'
      servers:
        - 127.0.0.1
    ha_disabled: true
    mysql:
      allow_remote_root: true
      root_network_acl: '%'
      server_debian_password: 'debian'
      server_root_password: 'root'
      server_repl_password: 'repl'
    openstack:
      developer_mode: true
      endpoints:
        compute-metadata-api:
          host: 'xxx.xxx.xxx.xxx'
          port: '8775'
      network:
        ng_l3:
          kitchen: true
    authorization:
      sudo:
        users:
          - vagrant
        passwordless: true

- name: compute
  run_list:
    - recipe[ktc-testing]
    - recipe[etcd::compile_time]
    - recipe[ktc-database]
    - recipe[ktc-memcached]
    - recipe[ktc-messaging]
    - recipe[ktc-identity]
    - recipe[ktc-monitor::client]
    - recipe[ktc-network::compute]
  attributes:
    etcd:
      args: '-c 127.0.0.1:4001 -s 127.0.0.1:7001 -f'
      servers:
        - 127.0.0.1
    ha_disabled: true
    mysql:
      allow_remote_root: true
      root_network_acl: '%'
      server_debian_password: 'debian'
      server_root_password: 'root'
      server_repl_password: 'repl'
    openstack:
      developer_mode: true
      endpoints:
        compute-metadata-api:
          host: 'xxx.xxx.xxx.xxx'
          port: '8775'
      network:
        ng_l3:
          kitchen: true
    authorization:
      sudo:
        users:
          - vagrant
        passwordless: true
