---
provisioner:
  name: chef_zero
  require_chef_omnibus: latest

driver:
  name: vagrant
  customize:
    memory: 512

platforms:
  - name: centos-6.4
  - name: ubuntu-12.04

suites:
- name: controller
  run_list:
    - recipe[ktc-testing]
    - recipe[etcd::compile_time]
    - recipe[ktc-monitor::client]
    - recipe[ktc-database]
    - recipe[ktc-memcached]
    - recipe[ktc-messaging]
    - recipe[ktc-identity]
    - recipe[ktc-network]
  attributes:
    etcd:
      args: '-c 127.0.0.1:4001 -s 127.0.0.1:7001 -f'
      servers:
        - 127.0.0.1
    ha_disabled: true
    mysql:
      allow_remote_root: true
      root_network_acl: '%'
      server_debian_password: 'debian'
      server_root_password: 'root'
      server_repl_password: 'repl'
    openstack:
      developer_mode: true
      endpoints:
        compute-metadata-api:
          host: 'xxx.xxx.xxx.xxx'
          port: '8775'
      network:
        ng_l3:
          kitchen: true
    authorization:
      sudo:
        users:
          - vagrant
        passwordless: true

- name: compute
  run_list:
    - recipe[ktc-testing]
    - recipe[etcd::compile_time]
    - recipe[ktc-monitor::client]
    - recipe[ktc-database]
    - recipe[ktc-memcached]
    - recipe[ktc-messaging]
    - recipe[ktc-identity]
    - recipe[ktc-network::compute]
  attributes:
    etcd:
      args: '-c 127.0.0.1:4001 -s 127.0.0.1:7001 -f'
      servers:
        - 127.0.0.1
    ha_disabled: true
    mysql:
      allow_remote_root: true
      root_network_acl: '%'
      server_debian_password: 'debian'
      server_root_password: 'root'
      server_repl_password: 'repl'
    openstack:
      developer_mode: true
      endpoints:
        compute-metadata-api:
          host: 'xxx.xxx.xxx.xxx'
          port: '8775'
      network:
        ng_l3:
          kitchen: true
    authorization:
      sudo:
        users:
          - vagrant
        passwordless: true
