AllCops:
  Includes:
    - metadata.rb
    - Gemfile
    - attributes/**
    - recipes/**
    - libraries/**
    - providers/**
    - resources/**
  Excludes:
    - test/**
    - vendor/**

MethodLength:
  Max: 30

LineLength:
  Max: 117

Encoding:
  Enabled: false
  Exclude:
    - metadata.rb
    - Gemfile
